
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 9000

km:
  server:
    ip: 127.0.0.1
    port: 6000